version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: monthly-expense-frontend:1.0.1
    ports:
      - "80:80"
    container_name: monthly-expense-frontend-app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: monthly-expense-backend:1.1.0
    ports:
      - "8081:8081"
    container_name: monthly-expense-backend-app
    depends_on:
      - db  # Add dependency on the database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/monthly_expense
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: docker  # Activate a specific profile if needed

  db:
    image: postgres:17  # Use a specific version for consistency
    ports:
      - "5432:5432"  # Expose the port for debugging (optional, remove in production)
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist data
    environment:
      POSTGRES_DB: monthly_expense_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

volumes:
  db_data:  # Define the volume for PostgreSQL data