apiVersion: v2
name: monthly-expense-app
description: A Helm chart for deploying the Monthly Expense Tracker application.
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: backend
    version: "0.1.0"
    repository: "file://charts/backend"
  - name: frontend
    version: "0.1.0"
    repository: "file://charts/frontend"