replicaCount: 1

image:
  repository: sandeepkamathkr/monthly-expense-backend
  tag: 1.3.4
  pullPolicy: Always

service:
  type: NodePort
  port: 8081
  nodePort: 30081

csvScheduler:
  enabled: true
  inputFolder: /app/csv-input
  defaultCurrency: AUD
  intervalMs: 300000

reprocessJob:
  enabled: false

csvInputVolume:
  persistentVolumeClaim:
    enabled: true
    size: 5Gi
    storageClass: ""  # leave empty to use cluster default StorageClass

